imports:
    - { resource: '@CleverAgeEAVManagerAkeneoProductBundle/Resources/config/base_config.yml' }

sidus_admin:
    configurations:
        products:
            controller: CleverAgeEAVManagerAkeneoEnterpriseBundle:Product
            entity: 'Product'
            prefix: /products
            actions:
                list:
                    path: /list
                    template: 'CleverAgeEAVManagerAkeneoEnterpriseBundle:Product:list.html.twig'
                edit:
                    path: /{identifier}/edit
                    form_type: CleverAge\EAVManager\AkeneoEnterpriseBundle\Form\Type\AkeneoProductType
                    template: 'CleverAgeEAVManagerAkeneoEnterprise/Product/edit.html.twig'
                editModel:
                    path:     /product/models/{family}/{code}/edit
                    defaults:
                        _controller: FrameworkBundle:Redirect:redirect
                        route: sidus_admin.product_models.edit
                        permanent: true
                apiSearch:
                    path: /_api/search/{endpoint}
            options:
                icon: shopping-cart
        product_models:
            # TODO handle darft and proposal for product model
            controller: CleverAgeEAVManagerAkeneoEnterpriseBundle:ProductModel
            entity: ~
            prefix: /product/models
            actions:
                list:
                    path: /list
                edit:
                    path: /{family}/{code}/edit
                    form_type: CleverAge\EAVManager\AkeneoEnterpriseBundle\Form\Type\AkeneoProductModelType
                    template: '@CleverAgeEAVManagerAkeneoEnterpriseBundle/Product/edit.html.twig'
        assets:
            controller: CleverAgeEAVManagerAkeneoEnterpriseBundle:Asset
            entity: 'Asset'
            prefix: /assets
            actions:
                viewReferenceFile:
                    path: /{assetCode}

# one uploader
oneup_uploader:
    mappings:
        product_asset:
            frontend: custom
            custom_frontend:
                class: 'CleverAge\EAVManager\AkeneoEnterpriseBundle\Controller\BlueimpController'
                name: akeneo_blueimp
            allowed_mimetypes: [ image/jpg, image/jpeg, image/png, image/gif ]
            storage:
                service: 'CleverAge\EAVManager\AkeneoEnterpriseBundle\Flysystem\Storage\ProductAssetStorage'
            namer: 'CleverAge\EAVManager\AkeneoEnterpriseBundle\Uploader\Naming\AssetNamer'
            error_handler: 'oneup_uploader.error_handler.blueimp'
oneup_flysystem:
    adapters:
        product_asset:
            custom:
                service: 'CleverAge\EAVManager\AkeneoEnterpriseBundle\Flysystem\Adapter\ProductAssetAdapter'
    filesystems:
        product_assets:
            adapter: product_asset


liip_imagine:
    loaders:
        assets:
            flysystem:
                filesystem_service: 'oneup_flysystem.product_assets_filesystem'

    filter_sets:
        asset_thumbnail:
            data_loader: assets
            quality: 70
            filters:
                auto_rotate: ~
                thumbnail: { size: [128, 128], mode: outbound }