parameters:
    eav_manager.akeneo.form.type.product.class: CleverAge\EAVManager\AkeneoEnterpriseBundle\Form\Type\AkeneoProductType
    eav_manager.akeneo.form.type.product_model.class: CleverAge\EAVManager\AkeneoEnterpriseBundle\Form\Type\AkeneoProductModelType

services:
    eav_manager.akeneo.form.type.product:
        class: '%eav_manager.akeneo.form.type.product.class%'
        autowire: true
        arguments:
            $transformer: '@CleverAge\EAVManager\AkeneoProductBundle\Form\Transformer\AkeneoProductTransformer'
        calls:
            - [setCache, ['@eav_manager.akeneo.api.cache']]
        tags:
            - { name: form.type }

    CleverAge\EAVManager\AkeneoEnterpriseBundle\Form\Type\AssetType:
        autowire: true
        tags:
            - { name: form.type }

    CleverAge\EAVManager\AkeneoEnterpriseBundle\Form\Type\AssetCollectionType:
        autowire: true
        tags:
        - { name: form.type }

